name: test

concurrency:
  # For PRs, later CI runs preempt previous ones. e.g. a force push on a PR
  # cancels running CI jobs and starts all new ones.
  #
  # For non-PR pushes, concurrency.group needs to be unique for every distinct
  # CI run we want to have happen. Use run_id, which in practice means all
  # non-PR CI runs will be allowed to run without preempting each other.
  group: ${{ github.workflow }}-$${{ github.pull_request.number || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - '**/*'
      - '!docs/**'
      - '!README.md'

jobs:
  build-windows:
    runs-on: windows
    steps:
      - uses: actions/checkout@v4
      - name: Gather info
        run: |
          ls env:
          get-command gcc
          gcc --version
          get-command clang
          clang --version
          gci -path c:\ -r -fi *gcc*.exe
